@Library('pipeline_templates') _

monorepoMavenAwsTemplate {
    // Nombre del proyecto al que pertenece este componente
    projectName = 'agencia-viajes'
    // path desde la raíz del repositorio para encontrar los fuentes del proyecto
    project_home_path = 'codigo/agencia-viajes-servicios/viajes-service'
    // path desde el project_home_path para encontrar el artefacto
    artifactPath = 'target'
    // nombre del repositorio en artifactory donde se guardarán los artefactos
    artifactoryRepoName = 'agencia-viajes'

    // regex para encontrar el reporte de test en formato JUnit, desde el project_home_path
    jUnitTestReport = 'target/surefire-reports/TEST-*.xml'

    // 'true' para que se ejecute el paso integration tests de IC, 'false' para que no se ejecute
    executeIntegrationTestIC = 'true'
    // regex para encontrar el reporte de integration-test en formato JUnit, desde el project_home_path
    jIntegrationTestReport = 'target/failsafe-reports/TEST-*.xml'

    awsRegion = 'us-west-2'
    awsEcrImageName = 'agencia-viajes/viajes-back'
    awsImageTag = '1.0'
    awsEcsFamilyTaskDefinition = 'agencia-viajes-viajes-back'
    awsEcsServiceName = 'agencia-viajes-back'

    // AWS Dllo
    awsIamProfileDllo = 'sura-integra-devops-jenkins-desarrollo'
    awsEcsUrlDllo = '913442950244.dkr.ecr.us-west-2.amazonaws.com'
    awsEcsClusterDllo = 'agencia-viajes-cluster '
    smokeTestUrlDllo = 'TODO'

    // 'true' para que se ejecute el paso integration tests (postman) en Dllo, 'false' para que no se ejecute
    executeIntegrationTestDllo = 'true'
    // URL para compartir la collection de Postman
    postmanCollectionUrl = 'https://www.getpostman.com/collections/5d482b2c07263cc38f6d'

    // 'true' para que se ejecute el paso E2E tests (SerenityBDD) en Dllo, 'false' para que no se ejecute
    executeE2eTestDllo = 'true'
    // URL del repositorio de SerenityBDD para el proyecto
    gitE2eUrl = 'TODO'
    // regex para encontrar el reporte de e2e test en formato JUnit, desde el home del proyecto SerenityBDD
    je2eTestReport = 'target/site/serenity/*.xml'
    // path donde se encuentra el index.html generado por SerenityBDD, desde el home del proyecto SerenityBDD
    htmle2eTestReport = 'target/site/serenity'

    // AWS QA
    awsIamProfileQa = 'TODO'
    awsEcsUrlQa = 'TODO'
    awsEcsClusterQa = 'cluster-agencia-viajes-test'
    smokeTestUrlQa = 'TODO'

    // 'true' para que se ejecute el paso integration tests (postman) en QA, 'false' para que no se ejecute
    executeIntegrationTestQa = 'false'

    // 'true' para que se ejecute el paso E2E tests (SerenityBDD) en Dllo, 'false' para que no se ejecute
    executeE2eTestQa = 'false'

    supportEmail = 'ronald.angulo@sura.pe'
}